# Dockerfile para desenvolvimento NestJS
FROM node:22.17.0

# Diretório de trabalho
WORKDIR /usr/src/app

# Copia apenas os arquivos necessários para instalar dependências
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o restante do código
COPY . .

# Expondo a porta padrão do NestJS
EXPOSE 3333

# Comando padrão para desenvolvimento (hot reload)
CMD ["npm", "run", "start:dev"] 