export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS_VERIFIED = 'EMAIL_ALREADY_EXISTS_VERIFIED',
  EMAIL_ALREADY_EXISTS_NOT_VERIFIED = 'EMAIL_ALREADY_EXISTS_NOT_VERIFIED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_CREATION_FAILED = 'USER_CREATION_FAILED',

  INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD',
  ESTABLISHMENT_PHONE_ALREADY_EXISTS = 'ESTABLISHMENT_PHONE_ALREADY_EXISTS',
  ESTABLISHMENT_NOT_FOUND_OR_ACCESS_DENIED = 'ESTABLISHMENT_NOT_FOUND_OR_ACCESS_DENIED',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',
  ESTABLISHMENT_SERVICE_NAME_ALREADY_EXISTS = 'ESTABLISHMENT_SERVICE_NAME_ALREADY_EXISTS',
}
